# ----
# Site

title: R[Ag]e Metals
url: "https://www.RageMetals.com"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Rage Metals is a small silver pouring company. We deal with artwork, generic bullion, and investment pieces.
author:
  name: R[Ag]e
  email: info@ragemetals.com
  phone: "+1 6183650808"
# -----
# Build
timezone: Etc/UTC

collections:
  staff_members:
    _hide_content: true
  products:
    _hide_content: true
    output: true
  raffles:
    _hide_content: true
    output: true

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-admin

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE